import Head from "next/head";
import React, { useEffect, useState, useRef, useId } from "react";
import SideBar from "../../../components/side-bar/SideBar";
import DashboardHeader from "../../../components/header/DashboardHeader";
import Link from "next/link";
import Job from "../../../components/job/Job";

const addJob = () => {
 

  return (
    <>
      <Head>
        <title>Create Job</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        
      </Head>
    
      <SideBar />
      <div className="dashboard sideBarOpen">
        <DashboardHeader />
        <div className="contentWrapper">
          <div className="dashboard_content">
            <div className="table--layout">
              <div className="go-back">
                <div>Create Job</div>
                <button className="creatButton label-success">
                  <Link href="/admin/jobs">Back to List</Link>
                </button>
              </div>
              <Job />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export const mapKey = "AIzaSyAdwF9cF9d7B6MIov5rw4JVUfXEST2TS9w"
export default addJob;
