import Head from "next/head";
import React, { useEffect, useState, useRef, useId } from "react";
import SideBar from "../../../../components/side-bar/SideBar";
import DashboardHeader from "../../../../components/header/DashboardHeader";
import Link from "next/link";
import DriverCustomerPassword from "../../../../components/change password/Driver&CustomerPassword";
import { useRouter } from "next/router";

const ChangePassword = () => {
  const router = useRouter();
  const id = router.query.driverId;
  return (
    <>
      <Head>
        <title>Update Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <SideBar />
      <div className="dashboard sideBarOpen">
        <DashboardHeader />
        <div className="contentWrapper">
          <div className="dashboard_content">
            <div className="table--layout">
              <div className="go-back">
                <div>Update Password</div>
                <button className="creatButton label-success">
                  <Link href="/admin/drivers">Back to List</Link>
                </button>
              </div>
              <DriverCustomerPassword id={id}/>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ChangePassword;
