import Head from "next/head";
import SideBar from "../../components/side-bar/SideBar";
import DashboardHeader from "../../components/header/DashboardHeader";
import { useState } from "react";
import { userService } from "../../services";
import { toast } from "react-toastify";

export default function AddNews() {
  const [category, setCategory] = useState("");
  const [type, setType] = useState("");

  const fetchNews = async (category, type) => {
    try {
      if (category.length < 1) {
        toast.error("Please select category", {
          position: toast.POSITION.TOP_RIGHT,
        });
        return;
      }
      if (type.length < 1) {
        toast.error("Please select type", {
          position: toast.POSITION.TOP_RIGHT,
        });
        return;
      }
      const response = await userService.fetchNewsAndSave(category, type);
      if (response?.data?.success) {
        toast.success(response.data.message, {
          position: toast.POSITION.TOP_RIGHT,
        });
      } else {
        toast.error(response.message, {
          position: toast.POSITION.TOP_RIGHT,
        });
      }
    } catch (error) {
      toast.error(error.message, {
        position: toast.POSITION.TOP_RIGHT,
      });
      return error.message;
    }
  };
  return (
    <>
      <Head>
        <title >Add News In Bulk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <SideBar />
      <div className="container dashboard sideBarOpen">
        <DashboardHeader message="Add News" />

        <div className="w-50">
          <div className="dashboard_content newLayout ">
            <div className="middle">
              <p className="catSel">Select Category For News</p>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault"
                  id="flexRadioDefault1"
                  checked={category === "sports" ? true : false}
                  onClick={() => setCategory("sports")}
                />
                <label className="form-check-label" for="flexRadioDefault1">
                  <strong> Sports</strong>
                </label>
              </div>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault"
                  id="flexRadioDefault2"
                  checked={category === "business" ? true : false}
                  onClick={() => setCategory("business")}
                />
                <label className="form-check-label" for="flexRadioDefault2">
                  <strong> Business</strong>
                </label>
              </div>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault"
                  id="flexRadioDefault2"
                  checked={category === "entertainment" ? true : false}
                  onClick={() => setCategory("entertainment")}
                />
                <label className="form-check-label" for="flexRadioDefault2">
                  <strong> Entertainment</strong>
                </label>
              </div>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault"
                  id="flexRadioDefault2"
                  checked={category === "health" ? true : false}
                  onClick={() => setCategory("health")}
                />
                <label className="form-check-label" for="flexRadioDefault2">
                  <strong> Health</strong>
                </label>
              </div>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault"
                  id="flexRadioDefault2"
                  checked={category === "general" ? true : false}
                  onClick={() => setCategory("general")}
                />
                <label className="form-check-label" for="flexRadioDefault2">
                  <strong> General</strong>
                </label>
              </div>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault"
                  id="flexRadioDefault2"
                  checked={category === "technology" ? true : false}
                  onClick={() => setCategory("technology")}
                />
                <label className="form-check-label" for="flexRadioDefault2">
                  <strong> Technology</strong>
                </label>
              </div>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault"
                  id="flexRadioDefault2"
                  checked={category === "science" ? true : false}
                  onClick={() => setCategory("science")}
                />
                <label className="form-check-label" for="flexRadioDefault2">
                  <strong> Science</strong>
                </label>
              </div>
            </div>
          </div>
        </div>
        <div className="w-50">
          <div className="dashboard_content newLayout ">
            <div className="middle">
              <p className="catSel">Select Type</p>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault12"
                  id="flexRadioDefault8"
                  checked={type === "all" ? true : false}
                  onClick={() => setType("all")}
                />
                <label className="form-check-label" for="flexRadioDefault8">
                  <strong> All</strong>
                </label>
              </div>
              <div className="form-check">
                <input
                  className="form-check-input"
                  type="radio"
                  name="flexRadioDefault12"
                  id="flexRadioDefault9"
                  checked={type === "major" ? true : false}
                  onClick={() => setType("major")}
                />
                <label className="form-check-label" for="flexRadioDefault9">
                  <strong> Major</strong>
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex-row">
        <button
          type="button"
          className="btn-success"
          onClick={() =>
            fetchNews(category, type) && console.log(category, type)
          }
        >
          Fetch
        </button>
      </div>
    </>
  );
}
