import React, { Fragment, useEffect, useState } from "react";
import DashboardHeader from "../../components/header/DashboardHeader";
import SideBar from "../../components/side-bar/SideBar";
import Head from "next/head";
import Image from "next/image";
import CountUp from "react-countup";
import BarChart from "../barchart";
import PieChart from "../piechart";
import LineChart from "../linechart";
import DoughnutChart from "../doughnut";
import { dashboardService } from "../../services";
import { toast } from "react-toastify";
import Link from "next/link";

// import 'react-tabs/style/react-tabs.css';

export default function Dashboard() {
  useEffect(() => {
    document.body.classList.add("has--tabs");
  });

  const [isLoading, setIsloading] = useState(true);
  const [refreshDashboard, setRefreshDashboard] = useState();
  const [dashboard, setDashboard] = useState();
  const delay = 1;

  useEffect(() => {
    getAnalyticsData();
    let timer = setTimeout(() => setIsloading(false), delay * 1000);
    return () => {
      clearTimeout(timer);
    };
  }, []);

  const getAnalyticsData = async () => {
    const resposne = await dashboardService.getAlldashboards();
    if (resposne.success) {
      toast.success(resposne.message, {
        position: toast.POSITION.TOP_RIGHT,
        toastId: resposne.message,
      });
      setDashboard(resposne);
    } else {
      console.log(resposne.message);
    }
  };

  return (
    <>
      <Head>
        <title>Welcome Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
      <div className="dashboard sideBarOpen">
        <DashboardHeader />
        <div className="contentWrapper" style={{ marginTop: "-50px" }}>
          <div className="dashboard_content">
            <h1 className="dashboard__title">Dashboard</h1>
            <div className="dashboard__tabs">
              <div className="dashboard__row row--grid__4">
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Total Users</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.totalUsers ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.1"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="45px"
                      >
                        <path
                          d="M0 0 C0.74121094 -0.0103125 1.48242188 -0.020625 2.24609375 -0.03125 C5.580118 0.73338288 7.21972446 2.02276952 9.5625 4.5 C10.15625 7.59375 10.15625 7.59375 10.0625 11 C10.0521875 12.1240625 10.041875 13.248125 10.03125 14.40625 C9.52384771 17.75510513 8.5587899 18.88264213 6.5625 21.5 C6.40318529 23.62906991 6.40318529 23.62906991 7.5625 25.5 C10.0571592 27.11546507 12.63919952 28.34965133 15.3125 29.64453125 C17.5625 31.5 17.5625 31.5 18.5625 38.5 C6.6825 38.5 -5.1975 38.5 -17.4375 38.5 C-16.4375 31.5 -16.4375 31.5 -13.93359375 29.28515625 C-12.41958984 28.43244141 -12.41958984 28.43244141 -10.875 27.5625 C-9.86308594 26.97597656 -8.85117187 26.38945313 -7.80859375 25.78515625 C-7.02613281 25.36105469 -6.24367188 24.93695313 -5.4375 24.5 C-6.05027612 21.53824877 -6.69122522 20.11941217 -8.4375 17.5 C-8.7734375 14.50390625 -8.7734375 14.50390625 -8.8125 11.0625 C-8.84085938 9.92941406 -8.86921875 8.79632813 -8.8984375 7.62890625 C-8.4375 4.5 -8.4375 4.5 -6.69140625 2.12109375 C-4.1942777 0.32506542 -3.03854749 -0.04212891 0 0 Z "
                          fill="#000000"
                          transform="translate(29.4375,11.5)"
                        />
                        <path
                          d="M0 0 C5.640625 -0.234375 5.640625 -0.234375 8.875 1.875 C11.85340473 6.25500695 11.78893858 9.84724492 11 15 C9.5 18.625 9.5 18.625 8 21 C8.95712891 21.52787109 8.95712891 21.52787109 9.93359375 22.06640625 C16.60217855 26.05091167 16.60217855 26.05091167 17.8203125 28.95703125 C18.0625 30.875 18.0625 30.875 18 34 C15.03 34 12.06 34 9 34 C8.79375 32.948125 8.5875 31.89625 8.375 30.8125 C7.14612199 26.46753847 4.6412281 24.62168423 1 22 C0.21625 21.401875 -0.5675 20.80375 -1.375 20.1875 C-1.91125 19.795625 -2.4475 19.40375 -3 19 C-2.125 14.125 -2.125 14.125 -1 13 C-0.76518307 10.81707226 -0.58636677 8.62796826 -0.4375 6.4375 C-0.35371094 5.23996094 -0.26992188 4.04242188 -0.18359375 2.80859375 C-0.12300781 1.88175781 -0.06242187 0.95492188 0 0 Z "
                          fill="#000000"
                          transform="translate(42,16)"
                        />
                        <path
                          d="M0 0 C0.04898437 0.90363281 0.09796875 1.80726562 0.1484375 2.73828125 C0.22320313 3.91777344 0.29796875 5.09726562 0.375 6.3125 C0.44460937 7.48425781 0.51421875 8.65601563 0.5859375 9.86328125 C0.78613747 13.15699887 0.78613747 13.15699887 3 16 C2.82136785 18.76609179 2.29356192 19.73611687 0.22265625 21.59765625 C-0.49019531 22.08105469 -1.20304687 22.56445312 -1.9375 23.0625 C-5.49254915 25.49490205 -7.60689327 27.30964104 -8.625 31.6875 C-8.74875 32.450625 -8.8725 33.21375 -9 34 C-11.97 34 -14.94 34 -18 34 C-18.05692925 31.1535375 -18.07969732 29.57584932 -17 27 C-14.22677341 24.58781612 -11.21237759 22.77167491 -8 21 C-8.495 20.21625 -8.99 19.4325 -9.5 18.625 C-11.4322124 13.95548671 -11.87972538 9.98787693 -11 5 C-7.71812442 0.17371239 -5.60215742 -0.23277662 0 0 Z "
                          fill="#000000"
                          transform="translate(18,16)"
                        />
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Total News</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.totalNews ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.0"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                        viewBox="0 0 321.000000 252.000000"
                        // preserveAspectRatio="xMidYMid meet"
                      >
                        <g
                          transform="translate(0.000000,252.000000) scale(0.100000,-0.100000)"
                          fill="#000000"
                          stroke="none"
                        >
                          <path
                            d="M354 2374 c-68 -33 -64 32 -64 -1031 0 -1105 -6 -1029 89 -1124 96
                            -95 11 -89 1191 -89 1180 0 1095 -6 1191 89 94 95 89 38 89 978 0 893 3 856
                            -60 888 -20 10 -59 15 -130 15 l-100 0 0 100 c0 117 -12 149 -64 174 -31 14
                            -132 16 -1073 16 -904 0 -1042 -2 -1069 -16z m2086 -981 c0 -483 5 -895 9
                            -917 11 -46 52 -92 97 -106 42 -14 70 -6 91 26 15 24 15 27 -4 52 -11 15 -31
                            29 -44 32 l-24 6 -3 747 -2 747 85 0 85 0 -2 -814 c-3 -805 -3 -815 -24 -842
                            -11 -15 -33 -37 -48 -48 -27 -21 -32 -21 -1086 -21 -1054 0 -1059 0 -1086 21
                            -15 11 -37 33 -48 48 -21 27 -21 36 -24 987 l-2 959 1015 0 1015 0 0 -877z"
                          />
                          <path
                            d="M657 2022 c-21 -23 -22 -56 -1 -76 14 -14 97 -16 769 -16 821 0 785
                            -3 785 55 0 58 36 55 -784 55 -717 0 -754 -1 -769 -18z"
                          />
                          <path
                            d="M657 1732 c-15 -16 -17 -55 -17 -335 0 -315 0 -316 22 -331 19 -14
                            68 -16 330 -16 295 0 309 1 328 20 19 19 20 33 20 328 0 262 -2 311 -16 330
                            -15 22 -16 22 -333 22 -295 0 -319 -1 -334 -18z m563 -327 l0 -235 -235 0
                            -235 0 0 228 c0 126 3 232 7 235 3 4 109 7 235 7 l228 0 0 -235z"
                          />
                          <path
                            d="M1523 1724 c-15 -24 -15 -29 -2 -53 l15 -26 321 -3 c349 -3 353 -2
                            353 53 0 54 -4 55 -350 55 l-320 0 -17 -26z"
                          />
                          <path
                            d="M1523 1434 c-15 -24 -15 -29 -2 -53 l15 -26 321 -3 c349 -3 353 -2
                            353 53 0 54 -4 55 -350 55 l-320 0 -17 -26z"
                          />
                          <path
                            d="M1523 1144 c-15 -24 -15 -29 -2 -53 l15 -26 321 -3 c349 -3 353 -2
                            353 53 0 54 -4 55 -350 55 l-320 0 -17 -26z"
                          />
                          <path
                            d="M656 864 c-21 -21 -20 -57 2 -78 17 -15 52 -16 338 -14 l318 3 15 26
                            c13 24 13 29 -2 53 l-17 26 -320 0 c-276 0 -321 -2 -334 -16z"
                          />
                          <path
                            d="M1523 854 c-15 -24 -15 -29 -2 -53 l15 -26 321 -3 c349 -3 353 -2
                            353 53 0 54 -4 55 -350 55 l-320 0 -17 -26z"
                          />
                          <path
                            d="M656 574 c-21 -21 -20 -57 2 -78 17 -15 52 -16 338 -14 l318 3 15 26
                            c13 24 13 29 -2 53 l-17 26 -320 0 c-276 0 -321 -2 -334 -16z"
                          />
                          <path
                            d="M1523 564 c-15 -24 -15 -29 -2 -53 l15 -26 321 -3 c349 -3 353 -2
                            353 53 0 54 -4 55 -350 55 l-320 0 -17 -26z"
                          />
                        </g>
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Total Categories</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.totalCategories ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.0"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                        viewBox="0 0 48.000000 48.000000"
                        preserveAspectRatio="xMidYMid meet"
                      >
                        <g
                          transform="translate(0.000000,48.000000) scale(0.100000,-0.100000)"
                          fill="#000000"
                          stroke="none"
                        >
                          <path
                            d="M89 391 c-38 -38 -38 -74 0 -112 38 -37 82 -39 116 -4 30 29 32 74 6
                            106 -25 31 -37 19 -22 -20 23 -55 -26 -99 -74 -67 -42 28 -27 80 28 99 10 4
                            15 11 12 17 -11 18 -36 11 -66 -19z"
                          />
                          <path
                            d="M276 394 c-32 -31 -13 -134 24 -134 17 0 21 20 6 26 -11 4 -16 19
                            -16 50 l0 44 45 0 45 0 0 -40 c0 -27 -5 -43 -15 -46 -8 -4 -15 -12 -15 -20 0
                            -17 32 -18 48 -2 18 18 15 103 -4 122 -21 21 -97 21 -118 0z"
                          />
                          <path
                            d="M286 204 c-35 -24 -38 -29 -33 -61 10 -61 31 -83 82 -83 48 0 85 24
                            66 43 -8 8 -15 7 -23 -1 -7 -7 -27 -12 -45 -12 -27 0 -35 5 -44 27 -13 36 -9
                            52 22 70 24 14 28 14 52 -2 15 -9 27 -26 27 -36 0 -11 7 -19 15 -19 31 0 17
                            48 -22 75 -47 31 -50 31 -97 -1z"
                          />
                          <path
                            d="M124 212 c-6 -4 -16 -17 -23 -29 -15 -30 6 -42 25 -14 9 12 19 19 24
                            16 8 -5 50 -81 50 -90 0 -3 -25 -5 -55 -5 -48 0 -54 2 -52 19 3 26 -13 31 -27
                            8 -8 -12 -8 -22 0 -35 9 -13 25 -17 79 -17 91 0 101 15 61 88 -30 52 -43 67
                            -61 67 -5 0 -15 -4 -21 -8z"
                          />
                        </g>
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Sports</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.sports ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.0"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                        viewBox="0 0 64.000000 64.000000"
                        preserveAspectRatio="xMidYMid meet"
                      >
                        <g
                          transform="translate(0.000000,64.000000) scale(0.100000,-0.100000)"
                          fill="#000000"
                          stroke="none"
                        >
                          <path
                            d="M486 555 c-19 -19 -20 -29 -6 -56 16 -28 68 -26 79 4 18 46 -38 86
                            -73 52z m61 -21 c8 -21 -19 -46 -40 -38 -17 6 -23 35 -10 47 12 13 44 7 50 -9z"
                          />
                          <path
                            d="M209 443 c-39 -36 -49 -52 -47 -72 5 -42 46 -40 88 4 26 27 42 35 69
                            35 l36 0 -144 -144 c-147 -147 -165 -177 -112 -184 19 -3 43 15 110 82 l87 86
                            29 -30 29 -30 -33 -34 c-36 -37 -40 -78 -7 -84 21 -4 126 93 126 117 0 7 -21
                            36 -46 63 l-46 49 23 25 c21 23 24 23 33 7 14 -28 27 -33 79 -33 57 0 87 14
                            87 40 0 23 -28 40 -64 40 -24 0 -26 4 -26 39 0 62 -16 71 -126 71 l-95 0 -50
                            -47z m251 9 c0 -10 -27 -44 -60 -77 -33 -33 -60 -66 -60 -74 0 -9 21 -37 47
                            -63 l47 -48 -49 -50 c-27 -28 -55 -50 -62 -50 -26 0 -24 23 6 54 17 18 31 38
                            31 46 0 8 -21 36 -47 62 l-47 48 64 65 64 65 -53 0 c-49 0 -58 -4 -97 -40 -47
                            -44 -61 -48 -71 -24 -4 10 9 31 38 60 l43 44 103 0 c92 0 103 -2 103 -18z m53
                            -90 c29 -3 37 -7 37 -23 0 -17 -7 -19 -65 -19 -64 0 -65 1 -65 27 0 14 7 35
                            17 45 16 17 17 17 27 -4 8 -17 22 -24 49 -26z m-313 -187 c-47 -47 -90 -85
                            -96 -85 -33 0 -14 33 64 112 77 78 88 86 101 73 14 -13 6 -25 -69 -100z"
                          />
                        </g>
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Entertainment</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.entertainment ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.0"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                        viewBox="0 0 50.000000 50.000000"
                        preserveAspectRatio="xMidYMid meet"
                      >
                        <g
                          transform="translate(0.000000,50.000000) scale(0.100000,-0.100000)"
                          fill="#000000"
                          stroke="none"
                        >
                          <path
                            d="M313 418 l-63 -62 -40 39 c-49 47 -67 39 -20 -10 l34 -35 -92 0
                            c-131 0 -132 -1 -132 -175 0 -187 -17 -175 250 -175 267 0 250 -12 250 175 0
                            174 -1 175 -132 175 l-92 0 57 58 c31 32 57 61 57 65 0 17 -19 3 -77 -55z m34
                            -131 c15 -14 18 -35 18 -112 0 -130 0 -130 -160 -130 -155 0 -158 2 -163 113
                            -4 87 8 128 40 142 13 5 73 9 135 7 93 -2 115 -5 130 -20z m99 -58 c10 -17
                            -13 -36 -27 -22 -12 12 -4 33 11 33 5 0 12 -5 16 -11z m0 -90 c10 -17 -13 -36
                            -27 -22 -12 12 -4 33 11 33 5 0 12 -5 16 -11z"
                          />
                        </g>
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Business</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.business ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.0"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                        viewBox="0 0 48.000000 48.000000"
                        preserveAspectRatio="xMidYMid meet"
                      >
                        <g
                          transform="translate(0.000000,48.000000) scale(0.100000,-0.100000)"
                          fill="#000000"
                          stroke="none"
                        >
                          <path
                            d="M182 405 c-14 -18 -30 -25 -54 -25 -48 0 -58 -15 -58 -86 l0 -61 46
                            -7 c60 -8 188 -8 248 0 l46 7 0 61 c0 71 -10 86 -58 86 -24 0 -40 7 -54 25
                            -15 19 -29 25 -58 25 -29 0 -43 -6 -58 -25z m88 -15 c0 -5 -13 -10 -30 -10
                            -16 0 -30 5 -30 10 0 6 14 10 30 10 17 0 30 -4 30 -10z m-100 -115 c0 -8 -7
                            -15 -15 -15 -16 0 -20 12 -8 23 11 12 23 8 23 -8z m168 -3 c2 -7 -3 -12 -12
                            -12 -9 0 -16 7 -16 16 0 17 22 14 28 -4z"
                          />
                          <path
                            d="M70 160 c0 -20 5 -41 12 -48 17 -17 299 -17 316 0 7 7 12 28 12 47
                            l0 36 -170 0 -170 0 0 -35z"
                          />
                        </g>
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>General</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.general ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.0"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                        viewBox="0 0 65.000000 65.000000"
                        preserveAspectRatio="xMidYMid meet"
                      >
                        <g
                          transform="translate(0.000000,65.000000) scale(0.100000,-0.100000)"
                          fill="#000000"
                          stroke="none"
                        >
                          <path
                            d="M298 448 l-25 -73 -71 -3 c-40 -2 -72 -6 -72 -11 0 -4 25 -25 55 -46
                            31 -21 54 -43 52 -49 -20 -50 -39 -127 -35 -132 4 -3 34 13 68 36 l62 42 59
                            -42 c70 -49 79 -42 49 45 -11 32 -17 62 -13 65 5 4 27 21 51 39 23 18 42 37
                            42 41 0 5 -30 10 -67 12 l-66 3 -21 62 c-32 95 -40 96 -68 11z"
                          />
                        </g>
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Health</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.health ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.0"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                        viewBox="0 0 50.000000 50.000000"
                        preserveAspectRatio="xMidYMid meet"
                      >
                        <g
                          transform="translate(0.000000,50.000000) scale(0.100000,-0.100000)"
                          fill="#000000"
                          stroke="none"
                        >
                          <path
                            d="M84 446 c-58 -26 -95 -100 -80 -161 5 -21 12 -25 46 -25 30 0 40 4
                            45 20 9 28 22 25 33 -7 8 -26 10 -24 21 32 23 112 33 111 51 -5 7 -44 16 -82
                            20 -85 4 -2 12 13 19 35 15 51 28 58 43 23 16 -37 18 -39 26 -26 4 6 27 12 52
                            14 35 3 45 1 45 -11 0 -11 -9 -14 -38 -12 -30 3 -41 -1 -57 -20 l-19 -23 -14
                            33 -14 34 -19 -53 c-10 -29 -23 -53 -29 -53 -5 0 -16 32 -23 70 -17 96 -18 96
                            -31 32 -7 -32 -16 -58 -21 -58 -4 0 -13 15 -20 33 -7 17 -14 26 -17 20 -3 -8
                            -22 -13 -44 -13 -21 0 -39 -3 -39 -7 0 -4 12 -24 26 -45 24 -34 52 -58 166
                            -141 l38 -28 89 66 c94 69 146 132 157 191 25 132 -105 230 -210 159 l-36 -24
                            -36 24 c-41 28 -83 31 -130 11z"
                          />
                        </g>
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Science</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.science ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.0"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                        viewBox="0 0 50.000000 50.000000"
                        preserveAspectRatio="xMidYMid meet"
                      >
                        <g
                          transform="translate(0.000000,50.000000) scale(0.100000,-0.100000)"
                          fill="#000000"
                          stroke="none"
                        >
                          <path
                            d="M252 488 c-7 -7 -12 -20 -12 -30 0 -14 -8 -18 -40 -18 -36 0 -40 -2
                            -40 -25 0 -25 1 -25 90 -25 89 0 90 0 90 25 0 14 -4 25 -10 25 -5 0 -10 8 -10
                            18 0 22 -19 42 -40 42 -9 0 -21 -5 -28 -12z m44 -19 c10 -17 -13 -36 -27 -22
                            -12 12 -4 33 11 33 5 0 12 -5 16 -11z"
                          />
                          <path
                            d="M180 341 c0 -32 -12 -59 -60 -133 -74 -115 -84 -152 -46 -185 26 -22
                            35 -23 176 -23 141 0 150 1 176 23 23 20 26 28 20 59 -3 19 -33 76 -66 126
                            -49 73 -60 98 -60 131 0 23 -4 41 -10 41 -18 0 -11 -84 10 -118 11 -18 20 -35
                            20 -37 0 -3 -40 -5 -90 -5 -50 0 -90 2 -90 5 0 2 9 19 20 37 21 34 28 118 10
                            118 -5 0 -10 -18 -10 -39z m45 -201 c0 -18 -6 -26 -23 -28 -13 -2 -25 3 -28
                            12 -10 26 4 48 28 44 17 -2 23 -10 23 -28z m115 -25 c15 -18 10 -45 -12 -59
                            -35 -22 -74 27 -48 59 16 19 44 19 60 0z"
                          />
                          <path
                            d="M220 345 c-15 -18 -10 -45 13 -59 34 -22 73 27 47 59 -16 19 -44 19
                            -60 0z m46 -16 c10 -17 -13 -36 -27 -22 -12 12 -4 33 11 33 5 0 12 -5 16 -11z"
                          />
                        </g>
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content tree--col flexBox col-4">
                  <div className="flex-1">
                    <div className="col--title first-caps first-letter">
                      <p>Technology</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                        <CountUp end={dashboard?.technology ?? 0} />
                      </p>
                    </div>
                  </div>
                  <div className="flex-2">
                    <div className="avtarBg">
                      <svg
                        version="1.1"
                        xmlns="http://www.w3.org/2000/svg"
                        width="48px"
                        height="48px"
                      >
                        <path
                          d="M0 0 C12.54 0 25.08 0 38 0 C38 12.54 38 25.08 38 38 C25.46 38 12.92 38 0 38 C0 25.46 0 12.92 0 0 Z M10 12 C10 16.62 10 21.24 10 26 C15.94 26 21.88 26 28 26 C28 21.38 28 16.76 28 12 C22.06 12 16.12 12 10 12 Z "
                          fill="#000000"
                          transform="translate(6,6)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(36,45)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(30,45)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(24,45)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(18,45)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(12,45)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(45,36)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(1,36)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(45,30)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(1,30)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(45,24)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(1,24)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(45,18)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(1,18)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(45,12)"
                        />
                        <path
                          d="M0 0 C1.32 0 2.64 0 4 0 C4 0.66 4 1.32 4 2 C2.68 2 1.36 2 0 2 C0 1.34 0 0.68 0 0 Z "
                          fill="#000000"
                          transform="translate(1,12)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(36,1)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(30,1)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(24,1)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(18,1)"
                        />
                        <path
                          d="M0 0 C0.66 0 1.32 0 2 0 C2 1.32 2 2.64 2 4 C1.34 4 0.68 4 0 4 C0 2.68 0 1.36 0 0 Z "
                          fill="#000000"
                          transform="translate(12,1)"
                        />
                      </svg>
                    </div>
                  </div>
                </div>
                <div className="col--content col--2 tickets--col no--icon">
                  <div className="col--title">
                    <p>Categories</p>
                  </div>
                  <div className="col--image">
                    <Image
                      src="/images/tickets.jpg"
                      layout="fill"
                      quality={100}
                    />
                    <PieChart dashboard={dashboard} />
                  </div>
                </div>
                {/* <div className="col--content map--image col--2 no--icon">
                        <div className="col--title">
                          <p>Jobs Per Months</p>
                        </div>
                        <div className="col--image">
                         <Image
                            src="/images/map.png"
                            layout="fill"
                            quality={100}
                          /> 
                           <BarChart dashboard={dashboard} /> 
                        </div>
                      </div> */}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
